# Generated by Django 4.1.5 on 2023-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incharge',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
